######################################################################
# Microsoft Visual C++ Makefile for the primecount console
# application and the primecount C++ library
# Usage: nmake -f Makefile.msvc
######################################################################

TARGET = primecount
CXX = cl /nologo
CXXFLAGS = /W2 /O2 /EHsc /D NDEBUG /I include /I primesieve-master\include
LINK = link /nologo /LIBPATH:primesieve-master
PRIMESIEVE_URL = https://github.com/kimwalisch/primesieve/archive/master.zip

LIB_OBJECTS = \
	src\balance_S2_load.obj \
	src\Li.obj \
	src\nth_prime.obj \
	src\phi.obj \
	src\PhiCache.obj \
	src\PhiTiny.obj \
	src\pi_legendre.obj \
	src\pi_lehmer.obj \
	src\pi_meissel.obj \
	src\pi_primesieve.obj \
	src\pmath.obj \
	src\popcount.obj \
	src\primecount.obj \
	src\P2.obj \
	src\P3.obj \
	src\test.obj \
	src\deleglise-rivat\pi_deleglise_rivat1.obj \
	src\deleglise-rivat\pi_deleglise_rivat2.obj \
	src\deleglise-rivat\pi_deleglise_rivat3.obj \
	src\deleglise-rivat\pi_deleglise_rivat_parallel1.obj \
	src\deleglise-rivat\pi_deleglise_rivat_parallel2.obj \
	src\lmo\FactorTable.obj \
	src\lmo\init_square_free.obj \
	src\lmo\pi_lmo1.obj \
	src\lmo\pi_lmo2.obj \
	src\lmo\pi_lmo3.obj \
	src\lmo\pi_lmo4.obj \
	src\lmo\pi_lmo5.obj \
	src\lmo\pi_lmo6.obj \
	src\lmo\pi_lmo_parallel1.obj \
	src\lmo\pi_lmo_parallel2.obj \
	src\lmo\pi_lmo_parallel3.obj \
	src\lmo\pi_lmo_parallel4.obj \
	src\lmo\S1.obj

APP_OBJECTS = \
	src\app\cmdoptions.obj \
	src\app\help.obj \
	src\app\main.obj

#-----------------------------------------------------------------------------
# Add /openmp if MSVC supports OpenMP
#-----------------------------------------------------------------------------

!IF ([$(CXX) /openmp /c src\has_openmp.cpp /Fonul > nul] == 0)
CXXFLAGS = /openmp $(CXXFLAGS)
!ENDIF

#-----------------------------------------------------------------------------
# Default targets
#-----------------------------------------------------------------------------

all: build_primesieve lib bin

#-----------------------------------------------------------------------------
# Automatically download and build primesieve
#-----------------------------------------------------------------------------

build_primesieve:
!IF !EXISTS(primesieve-master\primesieve.lib)
	@echo Downloading primesieve library...
	@powershell -Command (new-object System.Net.WebClient).DownloadFile('$(PRIMESIEVE_URL)', 'primesieve-master.zip')
	@echo Unzipping primesieve...
	@powershell -command "$$shellApplication = new-object -com shell.application; $$zipPackage = $$shellApplication.NameSpace('%cd%\primesieve-master.zip'); $$destinationFolder = $$shellApplication.NameSpace('%cd%'); $$destinationFolder.CopyHere($$zipPackage.Items())"
	@cd primesieve-master
	@nmake -f Makefile.msvc lib
	@cd..
!ENDIF

#-----------------------------------------------------------------------------
# Compilation rules
#-----------------------------------------------------------------------------

$(LIB_OBJECTS): $*.cpp
	$(CXX) $(CXXFLAGS) /c $*.cpp /Fo$@

$(APP_OBJECTS): $*.cpp
	$(CXX) $(CXXFLAGS) /c $*.cpp /Fo$@

#-----------------------------------------------------------------------------
# Build the primecount console application
#-----------------------------------------------------------------------------

bin: lib $(APP_OBJECTS)
	$(LINK) /OUT:$(TARGET).exe $(APP_OBJECTS) $(TARGET).lib primesieve.lib

#-----------------------------------------------------------------------------
# Build a static primecount.lib
#-----------------------------------------------------------------------------

lib: $(LIB_OBJECTS)
	lib.exe /nologo /OUT:$(TARGET).lib $**

#-----------------------------------------------------------------------------
# `nmake -f Makefile.msvc check` runs correctness tests
#-----------------------------------------------------------------------------

check test:
	$(TARGET).exe --test

#-----------------------------------------------------------------------------
# clean target
#-----------------------------------------------------------------------------

clean:
	-del /Q *.exe *.lib src\*.obj src\lmo\*.obj 2> /nul

#-----------------------------------------------------------------------------
# help target
#-----------------------------------------------------------------------------

help:
	@echo Usage: nmake -f Makefile.msvc
